[package]
name = "factors-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "CLI for factors unified factor library"

[lints]
workspace = true

[dependencies]
clap.workspace = true
factors.workspace = true

[[bin]]
name = "factors"
path = "src/main.rs"
